Error : when validating test17::main
 --> test_resources/templates/test17.yr:(6,4)
 6  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : undefined template call for test17::foo {F : fn (ref mut U, i32)-> Z, Z, U}(ref mut a : U)-> Z with {(x : i32, y)-> _}
    ┃  --> test_resources/templates/test17.yr:(8,16)
    ┃  8  ┃     let z = foo!{|x : i32, y| => { x + y }} (ref x);
    ┃     ╋                ^
    ┃     ┃ Error : incompatible types fn (ref mut i32, i32)-> i32 and fn (i32, i32)-> i32
    ┃     ┃  --> test_resources/templates/test17.yr:(8,18)
    ┃     ┃  8  ┃     let z = foo!{|x : i32, y| => { x + y }} (ref x);
    ┃     ┃     ╋                  ^
    ┃     ┃     ┃ Note :
    ┃     ┃     ┃  --> test_resources/templates/test17.yr:(2,13)
    ┃     ┃     ┃  2  ┃ fn foo {F : fn (ref mut U, i32)-> Z, Z, U} (ref mut a : U)-> Z {
    ┃     ┃     ┃     ╋             ^^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┃ Error : the call operator is not defined for test17::baz (_ : i32, _ : i32)-> void and {z : error, x : mut i32}
    ┃  --> test_resources/templates/test17.yr:(9,9)
    ┃  9  ┃     baz (z, x);
    ┃     ╋         ^
    ┃     ┃ Note : value z is of type error
    ┃     ┃  --> test_resources/templates/test17.yr:(9,10)
    ┃     ┃  9  ┃     baz (z, x);
    ┃     ┃     ╋          ^
    ┃     ┃     ┗━━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
