Error : when validating
 --> test_resources/lit_class/errors/test10.yr:(16,7)
16  ┃ class B {
    ╋       ^
    ┃ Error : the throwers of the overriden method impl::foo ()-> void are not compatible with the throwers of the ancestor method A::foo ()-> void
    ┃  --> test_resources/lit_class/errors/test10.yr:(11,12)
    ┃ 11  ┃     pub fn foo (self)
    ┃     ╋            ^^^
    ┃     ┃ Note :
    ┃     ┃ Error : the method might throw an exception of type test10::ErrorB, but that is not covered by the method of the ancestor class
    ┃     ┃  --> test_resources/lit_class/errors/test10.yr:(21,20)
    ┃     ┃ 21  ┃             throws ErrorB
    ┃     ┃     ╋                    ^^^^^^
    ┃     ┃     ┃ Note : throwing test10::Error
    ┃     ┃     ┗━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
