Error : when validating test3::main
 --> test_resources/control_flow/test3.yr:(1,4)
 1  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : conditional test is always evaluated to true, branch is always entered
    ┃  --> test_resources/control_flow/test3.yr:(3,12)
    ┃  3  ┃     if let [x, y, z] = a { // error, len of /a/ is /cte/
    ┃     ╋            ^
    ┃     ┗━━━━━━━    
    ┃ Error : conditional test is always evaluated to true, branch is always entered
    ┃  --> test_resources/control_flow/test3.yr:(9,15)
    ┃  9  ┃     if (a.len <= 3) {
    ┃     ╋               ^^
    ┃     ┗━━━━━━━    
    ┃ Error : conditional test is always evaluated to false, branch is never entered
    ┃  --> test_resources/control_flow/test3.yr:(12,15)
    ┃ 12  ┃     if (a.len >= 4) {
    ┃     ╋               ^^
    ┃     ┗━━━━━━━    
    ┃ Error : infinite loop with always true test is not allowed, rather use a loop construct
    ┃  --> test_resources/control_flow/test3.yr:(16,19)
    ┃ 16  ┃     } while a.len > 2;
    ┃     ╋                   ^
    ┃     ┗━━━━━━━    
    ┃ Error : do while loop test is always false, the loop is always entered just one time, so the branching construct is useless
    ┃  --> test_resources/control_flow/test3.yr:(19,19)
    ┃ 19  ┃     } while a.len > 4;
    ┃     ╋                   ^
    ┃     ┗━━━━━━━    
    ┃ Error : infinite loop with always true test is not allowed, rather use a loop construct
    ┃  --> test_resources/control_flow/test3.yr:(21,17)
    ┃ 21  ┃     while a.len <= 3 {
    ┃     ╋                 ^^
    ┃     ┗━━━━━━━    
    ┃ Error : loop test is always false, loop is never entered
    ┃  --> test_resources/control_flow/test3.yr:(24,17)
    ┃ 24  ┃     while a.len >= 4 {
    ┃     ╋                 ^^
    ┃     ┗━━━━━━━    
    ┗━━━━━┻━ 
