frame : test17::main ()-> void {
    let _ : i32 = loop {
            let a : (void)? = try {
                    {
                        ({
                            test17::foo (true);
                            break 12;
                            <unit-value>
                        })?
                    }
                } catch {
                    let #_catch : mut &(mut core::exception::Exception)
                    {
                        {.ok = false, .error = #_catch}
                    }
                };
            <unit-value>
        };
    <unit-value>
}
