fn main ()
    throws AssertError
{
    assert (false);
}
