
fn foo (i : i32)-> i32 {
    i
}

fn main ()
    throws AssertError
{
    let th : (future-> i32) = spawn foo (10);

    let _a_ = th.finished;
    assert (th.value == 10);
}
